name: DOU Scraper

on:
  schedule:
    # Run every hour from 1 AM to 9 AM BRT (4:00-12:00 UTC)
    - cron: '0 4-12 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # Add concurrency to prevent multiple workflows running simultaneously
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
      cancel-in-progress: true
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p log
        touch log/scraper.log
        
    - name: Run DOU scraper
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: "marcio.maron@advds.com.br"
        PYTHONUNBUFFERED: 1
      run: |
        python dou_scraper.py
        
    - name: Check for files
      run: |
        ls -la
        ls -la log/
        
    - name: Upload logs and database
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs-${{ github.run_number }}
        path: |
          ./log/**/*
          ./dou_scraper.db
          ./items.jl
          ./result.json 